package com.crussion.moissanite;

import net.fabricmc.api.ClientModInitializer;

import com.crussion.moissanite.ui.UiEntrypoints;
import com.crussion.moissanite.input.FakeKeybinds;
import com.crussion.moissanite.input.UiKeybinds;
import com.crussion.moissanite.definitions.UiDefinitions;
import com.crussion.moissanite.command.CommandReplacer;
import com.crussion.moissanite.command.MoissaniteCommands;
import com.crussion.moissanite.features.cheats.AutoExperiments;
import com.crussion.moissanite.features.cheats.AutoExperimentMacro;
import com.crussion.moissanite.features.cheats.AutoDirection;
import com.crussion.moissanite.features.cheats.AutoPearl;
import com.crussion.moissanite.features.cheats.AutoPearlRefill;
import com.crussion.moissanite.features.cheats.AutoRend_Reworked;
import com.crussion.moissanite.features.cheats.KuudraPosTracker;
import com.crussion.moissanite.features.cheats.RouteSystem;
import com.crussion.moissanite.features.cheats.WardrobeKeybinds;
import com.crussion.moissanite.features.dungeons.terminals.DungeonsTerminals;
import com.crussion.moissanite.features.general.GeneralTweaks;
import com.crussion.moissanite.features.general.Zoom;
import com.crussion.moissanite.features.mining.StructureScanner;
import com.crussion.moissanite.features.misc.AlwaysSprint;
import com.crussion.moissanite.features.misc.BurrowsNuker;
import com.crussion.moissanite.features.visual.KuudraEsp;
import com.crussion.moissanite.features.misc.WindowNameChanger;
import com.crussion.moissanite.features.visual.RenderImageOnScreen;
import com.crussion.moissanite.features.visual.storage.StorageOverlayFeature;
import com.crussion.moissanite.config.MoissaniteConfig;
import com.crussion.moissanite.spoofer.ClientSpoofer;
import com.crussion.moissanite.util.hypixel.SkyBlockLocationTracker;
import com.crussion.moissanite.util.kuudra.KuudraPhaseTracker;
import com.crussion.moissanite.features.kuudra.KuudraNoPre;
import com.crussion.moissanite.features.kuudra.KuudraRendDamage;
import com.crussion.moissanite.features.kuudra.KuudraSplits;
import com.crussion.moissanite.features.kuudra.KuudraBossHp;
import com.crussion.moissanite.features.kuudra.KuudraCubeHpTag;
import com.crussion.moissanite.features.kuudra.KuudraSupplyWaypoints;
import com.crussion.moissanite.features.kuudra.KuudraAutoPickupSupply;
import com.crussion.moissanite.features.kuudra.KuudraAutoShop;
import com.crussion.moissanite.features.kuudra.KuudraAutoTap;
import com.crussion.moissanite.features.kuudra.KuudraAutoOpenChest;
import com.crussion.moissanite.update.ModUpdater;
import com.crussion.moissanite.features.mining.UniqueServerHopper;

public class MoissaniteClient implements ClientModInitializer {
	@Override
	public void onInitializeClient() {
		UiDefinitions.init();
		WindowNameChanger.init();
		MoissaniteConfig.init();
		SkyBlockLocationTracker.init();
		CommandReplacer.init();
		ModUpdater.init();
		ClientSpoofer.init();
		UiEntrypoints.init();
		MoissaniteCommands.init();
		UiKeybinds.init();
		FakeKeybinds.init();
		GeneralTweaks.init();
		Zoom.init();
		WardrobeKeybinds.init();
		AutoExperiments.init();
		AutoExperimentMacro.init();
		AutoDirection.init();
		AutoPearl.init();
		AutoPearlRefill.init();
		RouteSystem.init();
		KuudraPhaseTracker.init();
		KuudraPosTracker.init();
		KuudraEsp.init();
		KuudraNoPre.init();
		KuudraRendDamage.init();
		KuudraSplits.init();
		KuudraBossHp.init();
		KuudraCubeHpTag.init();
		KuudraSupplyWaypoints.init();
		KuudraAutoPickupSupply.init();
		KuudraAutoShop.init();
		KuudraAutoTap.init();
		KuudraAutoOpenChest.init();
		AutoRend_Reworked.init();
		StructureScanner.init();
		UniqueServerHopper.init();
		AlwaysSprint.init();
		BurrowsNuker.init();
		RenderImageOnScreen.init();
		DungeonsTerminals.init();
		StorageOverlayFeature.init();
	}
}
